**service notes**

This labs provides hands-on experience with various AWS security and monitoring services, including AWS KMS, AWS Encryption CLI, Amazon Inspector, Amazon SNS, and Amazon CloudWatch.

In this labs i have learned how to:

Create an AWS KMS encryption key: I have created a new AWS KMS encryption key to demonstrate encryption and decryption capabilities.
Install the AWS Encryption CLI: I have installed the AWS Encryption CLI to encrypt and decrypt plaintext data.
Encrypt plaintext: I have used the AWS Encryption CLI to encrypt plaintext data using the KMS key created earlier.
Decrypt ciphertext: I have used the AWS Encryption CLI to decrypt the ciphertext generated.
Patch Linux instances using default baseline: I have demonstrate patching Linux instances using the default patch baseline.
Create custom patch baseline: I have create a custom patch baseline to demonstrate advanced patching capabilities.
Use patch groups to patch Windows instances using custom patch baseline: I have use patch groups to patch Windows instances using the custom patch baseline.
Verify patch compliance: I have verify the patch compliance of the instances patched in the previous steps.
Activate Amazon Inspector: I have activated Amazon Inspector to analyze and interpret vulnerability findings.
Analyze and interpret vulnerability findings: I have analyzed and interpret the vulnerability findings generated by Amazon Inspector.
Remediate the vulnerabilities found by Amazon Inspector: I have remediate the vulnerabilities found by Amazon Inspector.
Create an Amazon SNS notification: I have create an Amazon SNS notification to demonstrate alerting capabilities.
Configure a CloudWatch alarm: I have configure a CloudWatch alarm to trigger the SNS notification created.
Stress test an EC2 instance: I have stress test an EC2 instance to trigger the CloudWatch alarm.
Confirm that an Amazon SNS email was sent: I have confirm that an Amazon SNS email was sent as a result of the CloudWatch alarm.
Create a CloudWatch dashboard: I have created a CloudWatch dashboard to visualize metrics and alarms.
